# Generated by Django 3.2.6 on 2022-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0002_remove_quote_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
