# Generated by Django 3.2.7 on 2022-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0002_chatsnippet_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('likedBy', models.TextField(blank=True, default='')),
            ],
        ),
    ]
