# Generated by Django 3.2.6 on 2022-02-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(related_name='_junglechat_quote_tags_+', to='junglechat.Tag'),
        ),
    ]
