# Generated by Django 3.2.6 on 2022-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0004_auto_20220226_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
