# Generated by Django 3.2.6 on 2022-02-26 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='dateMade',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 2, 26)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
