# Generated by Django 3.2.6 on 2022-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junglechat', '0007_alter_usertoken_datemade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
