# Generated by Django 3.2.6 on 2021-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
