# Generated by Django 3.2.6 on 2021-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewtracker', '0002_alter_visitor_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='dates',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
