# Generated by Django 3.2.6 on 2021-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewtracker', '0003_visitor_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='JCVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userip', models.GenericIPAddressField()),
                ('freq', models.IntegerField(default=0)),
                ('loc', models.CharField(max_length=300)),
                ('dates', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KYTVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userip', models.GenericIPAddressField()),
                ('freq', models.IntegerField(default=0)),
                ('loc', models.CharField(max_length=300)),
                ('dates', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
