# Generated by Django 3.2.6 on 2021-10-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewtracker', '0004_auto_20211001_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kytvisitor',
            name='userip',
        ),
    ]
