# Generated by Django 3.2.6 on 2021-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayIndex', models.FloatField()),
                ('monthIndex', models.FloatField()),
                ('title', models.CharField(max_length=300)),
                ('channel', models.CharField(max_length=100)),
                ('titleLink', models.URLField(max_length=1000)),
                ('channelLink', models.URLField(max_length=1000)),
                ('moment', models.DateTimeField()),
            ],
        ),
    ]
