# Generated by Django 3.2.7 on 2022-06-21 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coreader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='numPages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='pdfPath',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='uiColor',
            field=models.CharField(default=4283215696, max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('accountType', models.CharField(default='google', max_length=20)),
                ('profilePicLink', models.CharField(default='https://i.imgur.com/vxP6SFl.png', max_length=1000)),
                ('identifier', models.CharField(default='', max_length=300)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('favouriteWords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreader.glossary')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreader.userprofilemodel'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
