# Generated by Django 3.2.7 on 2022-06-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreader', '0002_auto_20220621_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileModel',
            new_name='UserProfile',
        ),
    ]
