# Generated by Django 3.2.7 on 2022-06-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreader', '0003_rename_userprofilemodel_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossary',
            name='book',
        ),
        migrations.AddField(
            model_name='glossary',
            name='ownerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossary',
            name='ownerType',
            field=models.CharField(choices=[('user', 'user'), ('book', 'book')], default='book', max_length=20),
        ),
    ]
