# Generated by Django 3.2.7 on 2022-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreader', '0006_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
