# Generated by Django 3.2.7 on 2022-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreader', '0007_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uiColor',
            field=models.IntegerField(default=4283215696),
        ),
    ]
